apiVersion: v1
kind: Service
metadata:
  name: iot-ingestion-manager
  labels:
    app: iot-ingestion-manager
spec:
  ports:
  - port: 9900
  selector:
    app: iot-ingestion-manager
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iot-ingestion-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-ingestion-manager
    spec:
      hostNetwork: true
      containers:
      - name: iot-ingestion-manager
        image: 10.98.74.120:5000/daf-iot-ingestion-manager:1.0.0-bug178
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 9900
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/docker/conf/production.conf
          subPath: iot-ingestion-manager/conf/production.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/logback.xml
          subPath: iot-ingestion-manager/conf/logback.xml
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/daf.keytab
          subPath: iot-ingestion-manager/conf/daf.keytab
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
        - name: hbaseconf
          mountPath: /etc/hbase/conf
          readOnly: true
      imagePullSecrets:
        - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
      - name: hbaseconf
        hostPath:
          path: /etc/hbase/conf
